### PR TITLE
fix: aregister: Make multicommodity amounts are properly aligned in aregister.

### LINKED ISSUE #1656: Totals column misaligned in aregister when multiple commodities present. (since 1.21)
```
$ hledger -f examples/bcexample.hledger areg assets -w 80 -e 2012-01-05
Transactions in Assets and subaccounts:
2012-01-01 "Opening..  Eq:Openi..      3077.70 USD                   3077.70 USD
2012-01-01 "Allowed..  In:US:Fe..  17000.00 IRAUSD               17000.00 IRAUSD
                                                      3077.70 USD
2012-01-04 "BANK FE..  Ex:Fi:Fees        -4.00 USD               17000.00 IRAUSD
                                                      3073.70 USD
```

The misalignment actually gets quite severe in some cases, and in fact seems to align itself with the amounts column eventually, which is very confusing.

```
$ hledger -f examples/bcexample.hledger areg assets -w 80 -e 2012-01-10
Transactions in Assets and subaccounts:
2012-01-01 ..  E..                     3077.70 USD                   3077.70 USD
2012-01-01 ..  I..                 17000.00 IRAUSD               17000.00 IRAUSD
                                       3077.70 USD
2012-01-04 ..  E..                       -4.00 USD               17000.00 IRAUSD
                                       3073.70 USD
2012-01-05 ..  E..                 -1200.00 IRAUSD               15800.00 IRAUSD
                                       2550.60 USD                   5624.30 USD
                                        4.62 VACHR                    4.62 VACHR
2012-01-06 ..  E..                    -2400.00 USD               15800.00 IRAUSD
                                       3224.30 USD
                                        4.62 VACHR
2012-01-06 ..  I..                      600.00 USD               15800.00 IRAUSD
                                       3824.30 USD
                                        4.62 VACHR
2012-01-08 ..  E..                      -65.00 USD               15800.00 IRAUSD
                                       3759.30 USD
                                        4.62 VACHR
2012-01-08 ..  L..                     -140.36 USD               15800.00 IRAUSD
                                       3618.94 USD
                                        4.62 VACHR
2012-01-09 ..  A..                     -480.03 USD               15800.00 IRAUSD
                              4.862000000000 VBMPX                   3138.91 USD
                                        4.62 VACHR
                              4.862000000000 VBMPX
2012-01-09 ..  A..            6.273000000000 RGAGX               15800.00 IRAUSD
                                       -720.01 USD          6.273000000000 RGAGX
                                       2418.90 USD
                                        4.62 VACHR
                              4.862000000000 VBMPX
2012-01-09 ..  A..                     -240.01 USD               15800.00 IRAUSD
                              2.431000000000 VBMPX          6.273000000000 RGAGX
                                       2178.89 USD
                                        4.62 VACHR
                              7.293000000000 VBMPX
2012-01-09 ..  A..            3.136000000000 RGAGX               15800.00 IRAUSD
                                       -359.95 USD          9.409000000000 RGAGX
                                       1818.94 USD
                                        4.62 VACHR
                              7.293000000000 VBMPX
```

### PR DESCRIPTION
**Pull request by Xitian9**
Fixes #1656.

This also switches to the renderTable interface for laying out aregister, just as in postingsReport.

### CODE REVIEW

File: hledger/Hledger/Cli/Commands/Aregister.hs [hunk 1]
```diff
@@ -200,18 +210,13 @@ accountTransactionsReportItemAsText
...
-    (amtfirstline:amtrest) = take numlines $ amtlines ++ repeat "" -- posting amount is top-aligned
-    (balfirstline:balrest) = take numlines $ replicate (numlines - ballen) "" ++ ballines -- balance amount is bottom-aligned
-    spacer = T.replicate (totalwidth - (amtwidth + 2 + balwidth)) " "
+    amt = showamt change
+    bal = showamt balance
+    showamt = showMixedAmountLinesB noPrice{displayColour=color_}
+    -- Since this will usually be called with the knot tied between this(amt|bal)width and
+    -- preferred(amt|bal)width, make sure the former do not depend on the latter to avoid loops.
+    thisamtwidth = maximumDef 0 $ map wbWidth amt
+    thisbalwidth = maximumDef 0 $ map wbWidth bal
```
Comment (simonmichael) [inline hledger/Hledger/Cli/Commands/Aregister.hs:219]: Maybe this should be commented out too, like the knot-tying above ? I see it's being used though.

Comment (Xitian9) [reply hledger/Hledger/Cli/Commands/Aregister.hs:219]: I think I've concluded that the knot-tying can't be done in this way without causing a huge space leak. That probably means I can remove all that commented-out code, but maybe this should be done along with the register code as a separate PR.

Comment (simonmichael) [reply hledger/Hledger/Cli/Commands/Aregister.hs:219]: I didn't quite understand. For this PR, shouldn't we at least change this comment, since knot tying is currently not being used ?

Comment (Xitian9) [reply hledger/Hledger/Cli/Commands/Aregister.hs]: I've removed the relevant bits from Aregister.hs, and added another commit which removes the equivalent code in Register.hs.

**Comment by simonmichael** [comment]
Thanks!
