### PR TITLE
fix: csv: fix regression in parsing rules containing & (#2352)

### LINKED ISSUE #2352: 1.42: & in CSV rules no longer works, unescapable
`&` in the regex expression of an if block raises error on CSV import unless the `&` is followed by a conditional block. Escaping with backslashes or enclosing `&` in a regex group expression (e.g., `[ \&]*`) has no effect.

**Example CSV rule file**

```
if
%description STOP \& SHOP
    account2 Expenses:Food and Supplies
```

**Error Output**

```
hledger: Error: ...chase-visa.rules:137:21:
    |
137 | %description STOP \& SHOP
    |                     ^
unexpected space
expecting conditional block
```
I'm using hledger-flow import and hledger 1.42, mac-aarch64. I did not have this error prior to 1.42.

### PR DESCRIPTION
**Pull request by thomie**
Fixes #2352.

### CODE REVIEW

File: hledger-lib/Hledger/Read/RulesReader.hs [hunk 1]
```diff
@@ -1596,9 +1596,14 @@ tests_RulesReader = testGroup "RulesReader" [
...
 
+
   ,testGroup "regexp" [
     testCase "regexp.ends-before-&&" $
-      parseWithState' defrules (regexp empty) "A A && xxx" @?= (Right $ toRegexCI' "A A")
+      parseWithState' defrules (regexp eof) "A A && xxx" @?= (Right $ toRegexCI' "A A")
+   ,testCase "regexp contains &" $
+      parseWithState' defrules (regexp eof) "A & B" @?= (Right $ toRegexCI' "A & B")
+   ,testCase "regexp contains escaped &" $
+      parseWithState' defrules (regexp eof) "A \\& B" @?= (Right $ toRegexCI' "A \\& B")
```
Comment (simonmichael) [inline hledger-lib/Hledger/Read/RulesReader.hs:1606]: I don't think we support any backslash escaping here, so no need to test for it here or in csv.test.

**Comment by simonmichael** [comment]
Thanks!

File: hledger-lib/Hledger/Read/RulesReader.hs (hunk 1 above)
Comment (thomie) [reply hledger-lib/Hledger/Read/RulesReader.hs:1606]: Do you want to support escaping double ampersands?

2025-01-01,COFFEE && CODE,100
2025-01-02,COFFEE CODE,200

if
%description COFFEE \&\& CODE
    account2 expenses:bars

That's currently working: the rule only gets applied to the first line. But it's not documented nor tested.

Comment (simonmichael) [reply hledger-lib/Hledger/Read/RulesReader.hs:1606]: I'm releasing right now and we didn't discuss it, so I'll pass. That could use a bit more thinking about.
