### PR TITLE
Use with-utf8 and don't use Data.Text.IO.

### LINKED ISSUE #1154: Windows-built hledger executable fails in WSL
Hi!

I've encountered the following problem with character encoding.

My setup: 
- Win 10 with an Ubuntu18 in WSL
- hledger is built from source on the windows side:
```bash
bash $ hledger.exe --version
hledger 1.16.1
```
- locale in Ubuntu:
```bash
bash $ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL
```
- UTF-8 encoded journal

- run `hledger.exe -f journal register` inside WSL (launched via bash/conemu/ubuntu, no matter) to get
```bash
bash $ hledger.exe -f journal register
hledger.exe: E:\nosave\bookkeeping\journal: hGetContents: invalid argument (invalid byte sequence)
```
Yet on the windows side in a unicode-aware (via chcp 65001) powershell I get the correct output.

As suggested in the "troubleshooting" section in the manual, I tried running `LANG=something hledger -f journal register`; it does not help either for reasonable choice of "something".

What else can I try in this situation? Try to use an ubuntu-in-wsl-built version of hledger, maybe?

### LINKED ISSUE #1619: Data.Text.IO should not be used
[It has been documented](https://www.snoyman.com/blog/2020/10/haskell-bad-parts-1/) that `Data.Text.IO` does not play well with locales, and can cause problems. We should reduce/eliminate its use in our code, explicitly encoding to utf8 before writing the resulting ByteString.

[More context:
<https://www.snoyman.com/blog/2016/12/beware-of-readfile>
<https://hledger.org/install.html#check-your-locale>
<https://hledger.org/1.25/hledger.html#troubleshooting>
Basically by addressing this with [#1834](https://github.com/simonmichael/hledger/pull/1834) we aim to once and for all solve or at least reduce "hledger crashed because $LANG was unset / wrong for this file / the locale was not installed / [Nix](https://github.com/simonmichael/hledger/issues/1033)"-type reports (see also issues linked on #1834). --SM]

### PR DESCRIPTION
**Pull request by Xitian9**
fix: utf-8: Use with-utf8 to ensure all files are read and written with utf8 encoding. (Fixes #1619)

May also fix #1154, #1033, #708, #536, and #73. Testing is needed.

### CODE REVIEW

File: hledger-lib/Hledger/Utils.hs [hunk 1]
```diff
@@ -186,12 +184,7 @@ readFileOrStdinPortably f = openFileOrStdin f ReadMode >>= readHandlePortably
     openFileOrStdin f m   = openFile f m
 
 readHandlePortably :: Handle -> IO Text
-readHandlePortably h = do
-  hSetNewlineMode h universalNewlineMode
-  menc <- hGetEncoding h
-  when (fmap show menc == Just "UTF-8") $  -- XXX no Eq instance, rely on Show
-    hSetEncoding h utf8_bom
-  T.hGetContents h
+readHandlePortably h = hSetNewlineMode h universalNewlineMode *> TIO.hGetContents h
```
Comment (simonmichael) [inline hledger-lib/Hledger/Utils.hs:187]: IIRC, setting utf8_bom encoding made reading utf8 files more robust, by also accepting the utf8 bom prefix that some of them have. Why isn't this needed any more ?

Comment (simonmichael) [inline hledger-lib/Hledger/Utils.hs:187]: I think >> might be a little more idiomatic and obvious in this codebase

Comment (simonmichael) [inline hledger-lib/Hledger/Utils.hs:187]: Doesn't this read with the system locale's encoding as before ? Shouldn't we be enforcing utf8 now ?

**Comment by simonmichael** [comment]
PS, I'm a little confused, github says this has no conflicts with master but merging locally fails with either a bunch of conflicts or "refusing to merge unrelated branch". Is it PEBKAC or is there something odd about this branch ?

**Comment by simonmichael** [comment]
I remember we discussed this but I forgot where. This seems to have potential to be unexpectedly breaking and in that case quite annoying for users, so we should give it a detailed commit message (=> changelog/migration note), and ideally a preview release and a loud call for testing. I have missed apr 1 and may 1 but might still rush out a preview release when this lands.

File: hledger-lib/Hledger/Utils.hs (hunk 1 above)
Comment (Xitian9) [reply hledger-lib/Hledger/Utils.hs:187]: The reasoning was that I read something which recommended against it, which I thought was in the `with-utf8` documentation, but I cannot find it anymore. I can leave it in if you'd prefer.

Comment (Xitian9) [reply hledger-lib/Hledger/Utils.hs:187]: Sure thing.

Comment (Xitian9) [reply hledger-lib/Hledger/Utils.hs:187]: I believe it does. `openFile` comes from `with-utf8` (I'll qualify the import so that's more obvious), and `stdin` should be taken care of by the `withUtf8` wrapper around `main`.

Comment (Xitian9) [reply hledger-lib/Hledger/Utils.hs:187]: I think the issue is that `with-utf8` already sets the encoding, and so if we do it ourselves it will just be overridden. If setting the BOM is indeed desirable (which I have little knowledge of), it should probably be done upstream.

**Comment by Xitian9** [comment]
I've rebased onto master. I updated the commit message with a bit more detail, but my brain is too tired to have much of a go of it at the moment. Let me know if there are specific points you'd like addressed in the message.

**Comment by simonmichael** [comment]
For the record, we asked about adding https://en.wikipedia.org/wiki/Byte_order_mark support at  https://github.com/serokell/haskell-with-utf8/issues/14 and meanwhile @Xitian9 has kept our existing BOM support in place.  It seems to still be reasonably common to encounter it in the wild.

I have proposed we add a backward compatibility flag to restore old file reading behaviour anticipating a long tail of bug reports from users somehow relying on the old behaviour as they upgrade over the coming years. Let's revisit this after some testing.

**Comment by simonmichael** [comment]
Merged, release docs to follow. We may or may not add a flag to restore old reading behaviour  later if it seems worthwhile.

Otherwise, now that this has landed in master, any and all testing by folks with real-world non-ascii data is most welcome and helpful.

**Comment by simonmichael** [comment]
We decided to revert this for 1.26 (#1864) and contemplate it a bit more, following discussion eg on the mail list:
https://groups.google.com/g/hledger/c/0gFC7xtsteI/m/lX3Fn2veBQAJ
Thanks @Xitian9.
