### PR TITLE
lib: --forecast=PERIODICEXPR. Fixes #835, #1236

### LINKED ISSUE #835: start forecast transactions before today ? clarify forecast start/end rules
We currently have some functional tests failing due to --forecast being current-date-dependent. I think the [manual](http://hledger.org/manual.html#forecasting-with-periodic-transactions) is not quite right about forecast transactions' start date. It seems not possible to generate forecast transactions before today's date. Perhaps it should be.

### PR DESCRIPTION
**Pull request by adept**
Given that we already have a nice single place where "forecast begin" and "forecast end" is defined, plugging in options that allow overriding one or both of the values is pretty straightforward. I added a test nevertheless

### CODE REVIEW

File: hledger/Hledger/Cli/CliOptions.hs [hunk 1]
```diff
@@ -181,7 +181,9 @@ reportflags = [
 
   -- generated postings/transactions
  ,flagNone ["auto"]          (setboolopt "auto") "apply automated posting rules to modify transactions"
- ,flagNone ["forecast"]      (setboolopt "forecast") "generate future transactions from periodic transaction rules, for the next 6 months or till report end date. In hledger-ui, also make ordinary future transactions visible."
+ ,flagNone ["forecast"]      (setboolopt "forecast") "generate future transactions from periodic transaction rules, for the next 6 months or till report end date (could be overriden by --forecast-begin/--forecast-end). In hledger-ui, also make ordinary future transactions visible."
+ ,flagReq  ["forecast-begin"]     (\s opts -> Right $ setopt "forecast-begin" s opts) "DATE" "include forecast postings/txns on or after this date"
+ ,flagReq  ["forecast-end"]       (\s opts -> Right $ setopt "forecast-end" s opts) "DATE" "include forecast postings/txns before this date"
```
Comment (simonmichael) [inline hledger/Hledger/Cli/CliOptions.hs:186]: I like that you put "forecast" first, grouping these flags.

I wanted to improve the help somehow. What do you think of:
```
--forecast        generate periodic transactions (from periodic transaction rules).
                  By default these begin after the latest recorded transaction,
                  and end 6 months from today, or at the report end date.
                  Also, in hledger-ui, make future transactions visible.

--forecast-begin  generate periodic transactions from this date

--forecast-end    generate periodic transactions up to this date
```

These seem slightly redundant and verbose right now
(hledger --forecast --forecast-begin=...), I wonder if we can simplify.

File: tests/forecast.test [hunk 2]
```diff
@@ -156,3 +156,27 @@ Y 2000
...
+
+                  ||    Oct     Nov     Dec     Jan 
+==================++================================
+ assets:cash      ||  $1000   $1000    $400   $1000 
+ expenses:housing ||      0       0    $600       0 
+ income           || $-1000  $-1000  $-1000  $-1000 
+------------------++--------------------------------
+                  ||      0       0       0       0 
+>>>2
+>>>=0
```
Comment (simonmichael) [inline tests/forecast.test:182]: I wonder where in the manual this should be documented. I guess
https://hledger.org/hledger.html#general-options and 
https://hledger.org/journal.html#periodic-transactions.

File: hledger/Hledger/Cli/CliOptions.hs (hunk 1 above)
Comment (simonmichael) [reply hledger/Hledger/Cli/CliOptions.hs:186]: Eg (brainstorming):
```
--forecast | --forecast-in PERIODEXPR
--forecast [forecastdate:PERIODEXPR]  
```

Comment (simonmichael) [reply hledger/Hledger/Cli/CliOptions.hs:186]: Or, just say that using any of the three flags enables periodic transactions ? (hledger --forecast-begin ...  is enough).

**Comment by simonmichael** [comment]
I'll add more thoughts here, hope it's not too much.

**"forecast" or something else ?**
As you said [last year](https://github.com/simonmichael/hledger/issues/835#issuecomment-530413670), "forecast" implies future. Now we're allowing periodic transactions to be generated in the past as well, though that will be less common. We can keep calling it "forecast", I think it's ok. Or we could look for a new name, eg `--auto-transactions` (and make `--auto` short for `--auto-transactions --auto-postings`), or something else, though also with `--forecast` as an alias.

**begin/end or from/to ?**
Whatever we X choose above, should it be --X-begin/--X-end, or --X-from/--X-to ? The first is consistent with --begin and --end, helping to show that --begin/--end/--forecast-begin/--forecast-end are the four dates affecting a report. The second reads a little more naturally and grammatically. What's your preference ?

**showing future transactions in hledger-ui ?**
--forecast has a second function of revealing future-dated transactions in hledger-ui (hidden by default). If we allow any of --forecast, --forecast-begin, --forecast-end to enable periodic transactions, would all of them also do the thing in hledger-ui ? If the "forecast" period is in the past that would be unintuitive.

File: hledger/Hledger/Cli/CliOptions.hs (hunk 1 above)
Comment (simonmichael) [reply hledger/Hledger/Cli/CliOptions.hs:186]: Yet another:
```
--forecast-period PERIODEXPR
```

**Comment by adept** [comment]
I'd like to keep `--forecast` because supplying PERIODEXPR does not necessary mean that we are talking about the past -- some accounts could be more in the future than the others, and implicitly taking date of the last transaction in the journal as the start of the forecast might imply that we are "going to the future". In this case, using PERIODEXPR means that we simply restore the status quo.

I've just pushed the rework that makes `--forecast` accept optional PERIODEXPR. When omitted, it will default to current defaults

File: hledger/Hledger/Cli/CliOptions.hs (hunk 1 above)
Comment (adept) [reply hledger/Hledger/Cli/CliOptions.hs]: For posterity: i took the help text and tried to shoot for `--forecast[=PERIODICEXPR]`

File: tests/forecast.test (hunk 2 above)
Comment (adept) [reply tests/forecast.test:182]: I added help to the section about `--forecast`

**Comment by simonmichael** [comment]
Thanks!
