### PR TITLE
web: fix links from transaction register to journal for multiple journal files (#1041)

### LINKED ISSUE #1041: hledger-web: register's date links are wrong with multiple input files
In `http://localhost:5000/register?q=inacct%3A"MyAccount"`
I can click on a transaction date.
This gets me to, say, `http://localhost:5000/journal#transaction-167`
but the fragment `transaction-167` has the wrong number.
I am using multiple input files and the transactions are not strictly ordered by date.
I should prepare a small example, but maybe you can already confirm the problem with your data?

### PR DESCRIPTION
**Pull request by thielema**

### CODE REVIEW

File: hledger-web/Hledger/Web/Widget/Common.hs [hunk 1]
```diff
@@ -106,6 +107,9 @@ mixedAmountAsHtml b _ =
       Just True -> "negative amount"
       _ -> "positive amount"
 
-transactionFrag :: Transaction -> String
-transactionFrag t =
-    printf "transaction-%s-%d" (sourceFilePath $ tsourcepos t) (tindex t)
+transactionFragment :: Journal -> Transaction -> String
+transactionFragment j =
+    let hm = HashMap.fromList $ zip (map fst $ jfiles j) [(0::Integer) ..]
```
Comment (simonmichael) [inline hledger-web/Hledger/Web/Widget/Common.hs:112]: How about starting file ids from 1, since we do that for transactions ?

File: hledger-web/hledger-web.cabal [hunk 2]
```diff
@@ -185,6 +185,7 @@ library
     , time >=1.5
     , transformers
     , unix-compat
+    , unordered-containers
```
Comment (simonmichael) [inline hledger-web/hledger-web.cabal:188]: Would you mind adding this to package.yaml to stop warnings.

**Comment by thielema** [comment]
On Sun, 24 May 2020, Simon Michael wrote:

> @simonmichael requested changes on this pull request.
> 
> Thank you very much! Small comments added.

I altered my commits accordingly.

**Comment by simonmichael** [comment]
Thanks for the fix @thielema .
