### PR TITLE
fix: budget: Make sure boring parents of unbudgeted accounts are not

### LINKED ISSUE #1800: Budget reports with --empty don't correctly handle unbudgeted accounts with boring budgeted parents.
Pointed out by @holmescharles in #939 [starting [here](https://github.com/simonmichael/hledger/issues/939#issuecomment-1006609347)]. Copied over here since it deserves its own issue.

```
~ monthly from 2019/01
    expenses:personal             $1,000.00
    liabilities

2019/01/01 Google home hub and home mini x2
    expenses:personal:electronics          $10.00
    liabilities                           $-10.00
```

```
$ hledger -f foo balance --budget -E -M --tree
Budget performance in 2019-01:

                               ||                       Jan
===============================++===========================
 expenses:personal             ||       0 [0% of $1,000.00]
 expenses:personal:electronics ||  $10.00
 liabilities                   || $-10.00 [1% of $-1000.00]
-------------------------------++---------------------------
                               ||       0 [              0]
```

### PR DESCRIPTION
**Pull request by Xitian9**
elided if they have a budget. (Fixes #1800)

This only affects calls with --budget and -E, but not with --no-elide.

### CODE REVIEW

File: hledger-lib/Hledger/Reports/MultiBalanceReport.hs [hunk 1]
```diff
@@ -102,16 +104,17 @@ type ClippedAccountName = AccountName
...
-multiBalanceReportWith :: ReportSpec -> Journal -> PriceOracle -> MultiBalanceReport
-multiBalanceReportWith rspec' j priceoracle = report
+-- | A helper for multiBalanceReport. This one takes some extra arguments,
+-- a 'PriceOracle' to be used for looking up market prices, and a set of
+-- 'AccountName's which should always be displayed in the final report.
+-- Commands which run multiple reports (bs etc.) can generate the price oracle
+-- just once for efficiency, passing it to each report by calling this function
+-- directly.
+multiBalanceReportWith :: ReportSpec -> Journal -> PriceOracle -> Set AccountName -> MultiBalanceReport
+multiBalanceReportWith rspec' j priceoracle specialaccts = report
```
Comment (simonmichael) [inline hledger-lib/Hledger/Reports/MultiBalanceReport.hs:117]: Sorry for the fragmentary review. How would you feel about renaming specialaccts to unelidableaccts everywhere, for a bit more clarity ?

Comment (Xitian9) [reply hledger-lib/Hledger/Reports/MultiBalanceReport.hs:117]: Sure thing.

**Comment by simonmichael** [comment]
Thanks!
