### PR TITLE
fix!: register: Tighten up spacing around the date in register reports. (#1655)

### LINKED ISSUE #1655: reg: report intervals with custom start dates are hard to read
When showing https://hledger.org/dev/hledger.html#intervals-with-custom-start-date , in general `register` must display both the start and end date for each period, but it doesn't allow enough width in the first column. `aregister` might have the same problem.

### PR DESCRIPTION
**Pull request by Xitian9**
Fixes #1655.

As a side effect, this changes the Json representation of the PostingsReport. The maybe report end date is now replaced with a maybe period.

I think this will provide strictly more information, and so is a desirable change, but if it will break too much we can change it back.

### CODE REVIEW

**Comment by Xitian9** [comment]
We seem to be getting some early build failures due to one of the check rules regarding commit messages.

**Comment by Xitian9** [comment]
The last commit message doesn't begin with a `;`, but it still seems to be skipping the CI tests.

**Comment by simonmichael** [comment]
Yes, you can see the `git log` failing with
```
fatal: ambiguous argument 'origin/regalign': unknown revision or path not in the working tree.
```
That hard-coded `origin` seems not to be working for PRs (any more ? things were working somehow before). It's rather hard to see how to reliably list the new commits in github CI. We could open an issue, otherwise I'll just keep tweaking here and there.

**Comment by simonmichael** [comment]
(And, pushed another fix. Thanks for pointing it out.)

File: hledger-lib/Hledger/Reports/PostingsReport.hs [hunk 1]
```diff
@@ -38,27 +38,25 @@ import Hledger.Reports.ReportOptions
...
+                          ,MixedAmount   -- The running total after this posting, or with --average,
+                                         -- the running average posting amount. With --historical,
+                                         -- postings before the report start date are included in
+                                         -- the running total/average.
                           )
 
 -- | A summary posting summarises the activity in one account within a report
 -- interval. It is kludgily represented by a regular Posting with no description,
 -- the interval's start date stored as the posting date, and the interval's end
 -- date attached with a tuple.
```
Comment (simonmichael) [inline hledger-lib/Hledger/Reports/PostingsReport.hs:58]: My comment here looks a bit sketchy.. and out of date now, hopefully ?

File: hledger/test/cli/report-interval.test [hunk 2]
```diff
@@ -13,22 +13,22 @@
 # The last report interval option takes precedence.
 
 $ hledger -f- register --weekly --monthly
-2019-01                 a                                        2             2
-2019-02                 a                                        1             3
+2019-01   a                                                      2             2
```
Comment (simonmichael) [inline hledger/test/cli/report-interval.test:16]: Any particular reason it's 3 spaces ? I think 2 is our normal minimum inter-field separator.

File: hledger-lib/Hledger/Reports/PostingsReport.hs (hunk 1 above)
Comment (simonmichael) [reply hledger-lib/Hledger/Reports/PostingsReport.hs:58]: Sorry, I may have misclicked. I'm wondering if the "It is kludgily represented..." haddock needs updating.

File: hledger/test/cli/report-interval.test (hunk 2 above)
Comment (Xitian9) [reply hledger/test/cli/report-interval.test:16]: I'll look at tightening that up further.

Comment (Xitian9) [reply hledger/test/cli/report-interval.test:16]: Ah, got it. It's actually 1 space between the date and the description, a 0 width empty description, then 2 spaces between the description and the account, for 3 spaces total separation in this case.

File: hledger-lib/Hledger/Reports/PostingsReport.hs (hunk 1 above)
Comment (Xitian9) [reply hledger-lib/Hledger/Reports/PostingsReport.hs]: You are correct. I've updated it.

File: hledger/test/cli/report-interval.test (hunk 2 above)
Comment (simonmichael) [reply hledger/test/cli/report-interval.test:16]: Ok. It looked a little weird to me but I think you're saying it's fine and good as is.

**Comment by simonmichael** [comment]
Thanks!
