### PR TITLE
import: fix scoping problems with match groups

### LINKED ISSUE #2158: CSV: match group references get mixed up when multiple ifs match a record
When reading CSV and _rules_ files and using REGEX expressions, if more than one `if` block matches the same record, the REGEX group index gets mixup.

## Example:

* CSV file:

```csv
date,desc
2019-01-01,SUFFIX First
2019-02-01,SUFFIX Text 1 - Text 2
```

* Rules file:

```
skip          1

fields        date,desc
separator     ,
date-format   %Y-%m-%d
description   Test

if %desc SUFFIX (.*)
  account1      account:\1
  amount1       1
  account2      equity

if %desc SUFFIX (.*) - (.*)
  account1      account:\1:\2
  amount1       1
  account2      equity
```

## Expected Result

```
2019-01-01 Test
    account:First               1
    equity

2019-02-01 Test
    account:Text 1:Text 2               1
    equity
```

## Current Result

```
2019-01-01 Test
    account:First               1
    equity

2019-02-01 Test
    account:Text 1 - Text 2:Text 1               1
    equity
```

## Note

If the rules file is modified with the following:

```
if %desc SUFFIX (.*) - (.*)
  account1      account:\2:\3
  amount1       1
  account2      equity
```

(note the index for matching groups (`\2` and `\3`), then the result works as expected.

## More info

HLedger version: `hledger 1.32.2, mac-aarch64`

[Background: wish #2009, pr #2087. 
Workaround: don't allow multiple ifs with capture groups to match the same CSV record. So if you use capture groups, make those regexps specific enough that at most one of them will match any given CSV record.]

### PR DESCRIPTION
**Pull request by jmtd**
This is a beginning of an attempt to fix #2158. First a test to capture the problem:

```
    issue-2158:                   FAIL
      /home/jon/git/hledger/hledger-lib/Hledger/Read/RulesReader.hs:1547:
      expected: Just "account:Text 1:Text 2"
       but got: Just "account:Text 1 - Text 2:Text 1"
```

I'm not sure why the order of `rconditionalblocks` appears to be reversed from the order in rules files. That's where I'll look when I next pick this up.

### CODE REVIEW

**Comment by jmtd** [comment]
>  I'm not sure why the order of rconditionalblocks appears to be reversed from the order in rules files. 

Probably relevant: https://github.com/simonmichael/hledger/blob/master/hledger-lib/Hledger/Read/RulesReader.hs#L457

**Comment by jmtd** [comment]
I think this is nearly there.

 - [ ] I've had to (temporarily?) adjust `regexMatchValue` to use `rconditionalblocks` rather than `rblocksassigning`, as I'm not  sure yet how to update that field to reflect an altered set of ConditionalBlocks
 - [ ] `Maybe (Either FieldTemplate ConditionalBlock)` is a bit of a mouthful. We could introduce a type alias for the `Either` bit. On the other hand, the function is now only used in two places, so perhaps that's overkill.
 - [ ] I don't know how legible `hledgerField` and `hledgerFieldValue` are. I've been staring at them too long to judge right now.
 - [ ] The new unit tests need cleaning up; I've left dev experiments and comments and suchlike there

File: hledger-lib/Hledger/Read/RulesReader.hs [hunk 1]
```diff
@@ -728,15 +737,22 @@ maybeNegate _ origbool = origbool
 -- Note conditional blocks' patterns are matched against an approximation of the
 -- CSV record: all the field values, without enclosing quotes, comma-separated.
 --
-getEffectiveAssignment :: CsvRules -> CsvRecord -> HledgerFieldName -> Maybe FieldTemplate
-getEffectiveAssignment rules record f = lastMay $ map snd $ assignments
+getEffectiveAssignment
```
Comment (simonmichael) [inline hledger-lib/Hledger/Read/RulesReader.hs:740]: I think a couple of comments & haddocks might need updating, eg lines 734 and 751.

**Review by simonmichael — CHANGES_REQUESTED** [review]
Just a minor thing. I haven't understood every detail but this is looking and sounding great.

File: hledger-lib/Hledger/Read/RulesReader.hs [hunk 2]
```diff
@@ -730,9 +731,10 @@ maybeNegate :: MatcherPrefix -> Bool -> Bool
 maybeNegate Not origbool = not origbool
 maybeNegate _ origbool = origbool
 
--- | Given the conversion rules, a CSV record and a hledger field name, find
--- the value template ultimately assigned to this field, if any, by a field
--- assignment at top level or in a conditional block matching this record.
+-- | Given the conversion rules, a CSV record and a hledger field name, collect
+-- the value templates (and their parent Conditional Blocks where applicable)
+-- assigned to this field, if any, by top-level field assignments and
+-- conditional blocks matching this record.
```
Comment (simonmichael) [inline hledger-lib/Hledger/Read/RulesReader.hs:737]: Excuse quibbling, it's because I expect I'll be staring confusedly at this file in future:

"find the value template" changed to "collect the value templates (and their parent Conditional Blocks where applicable)".

but the type signature looks more like "find a single template or its parent conditional block" ?

Comment (jmtd) [reply hledger-lib/Hledger/Read/RulesReader.hs:737]: You're absolutely right; I forgot that `getEffectiveAssignment` applied `lastMay` to the list, I thought it was done by its callers (it was in an earlier revision of mine). I'll address it.

**Comment by simonmichael** [comment]
Thanks for the fix @jmtd!

(I tried to merge keeping history, probably made a mess as usual..)

**Comment by alerque** [comment]
Thanks for the work on this! I'm looking forward to being able to use it.

Which reminds me I need to get that Nix Flake working so I can run arbitrary versions in production...
